# openSilexTestAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' BrapiGermplasmDTO Class
#'
#' @field accessionNumber 
#' @field acquisitionDate 
#' @field biologicalStatusOfAccessionCode 
#' @field breedingMethodDbId 
#' @field commonCropName 
#' @field countryOfOrigin 
#' @field defaultDisplayName 
#' @field documentationURL 
#' @field donors 
#' @field genus 
#' @field germplasmGenus 
#' @field germplasmDbId 
#' @field germplasmName 
#' @field germplasmPUI 
#' @field germplasmSpecies 
#' @field instituteCode 
#' @field instituteName 
#' @field pedigree 
#' @field seedsource 
#' @field species 
#' @field speciesAuthority 
#' @field subtaxa 
#' @field subtaxaAuthority 
#' @field synonyms 
#' @field taxonIds 
#' @field typeOfGermplasmStorageCode 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BrapiGermplasmDTO <- R6::R6Class(
  'BrapiGermplasmDTO',
  public = list(
    `accessionNumber` = NULL,
    `acquisitionDate` = NULL,
    `biologicalStatusOfAccessionCode` = NULL,
    `breedingMethodDbId` = NULL,
    `commonCropName` = NULL,
    `countryOfOrigin` = NULL,
    `defaultDisplayName` = NULL,
    `documentationURL` = NULL,
    `donors` = NULL,
    `genus` = NULL,
    `germplasmGenus` = NULL,
    `germplasmDbId` = NULL,
    `germplasmName` = NULL,
    `germplasmPUI` = NULL,
    `germplasmSpecies` = NULL,
    `instituteCode` = NULL,
    `instituteName` = NULL,
    `pedigree` = NULL,
    `seedsource` = NULL,
    `species` = NULL,
    `speciesAuthority` = NULL,
    `subtaxa` = NULL,
    `subtaxaAuthority` = NULL,
    `synonyms` = NULL,
    `taxonIds` = NULL,
    `typeOfGermplasmStorageCode` = NULL,
    initialize = function(`accessionNumber`, `acquisitionDate`, `biologicalStatusOfAccessionCode`, `breedingMethodDbId`, `commonCropName`, `countryOfOrigin`, `defaultDisplayName`, `documentationURL`, `donors`, `genus`, `germplasmGenus`, `germplasmDbId`, `germplasmName`, `germplasmPUI`, `germplasmSpecies`, `instituteCode`, `instituteName`, `pedigree`, `seedsource`, `species`, `speciesAuthority`, `subtaxa`, `subtaxaAuthority`, `synonyms`, `taxonIds`, `typeOfGermplasmStorageCode`){
      if (!missing(`accessionNumber`)) {
        stopifnot(is.character(`accessionNumber`), length(`accessionNumber`) == 1)
        self$`accessionNumber` <- `accessionNumber`
      }
      if (!missing(`acquisitionDate`)) {
        stopifnot(is.character(`acquisitionDate`), length(`acquisitionDate`) == 1)
        self$`acquisitionDate` <- `acquisitionDate`
      }
      if (!missing(`biologicalStatusOfAccessionCode`)) {
        stopifnot(is.character(`biologicalStatusOfAccessionCode`), length(`biologicalStatusOfAccessionCode`) == 1)
        self$`biologicalStatusOfAccessionCode` <- `biologicalStatusOfAccessionCode`
      }
      if (!missing(`breedingMethodDbId`)) {
        stopifnot(is.character(`breedingMethodDbId`), length(`breedingMethodDbId`) == 1)
        self$`breedingMethodDbId` <- `breedingMethodDbId`
      }
      if (!missing(`commonCropName`)) {
        stopifnot(is.character(`commonCropName`), length(`commonCropName`) == 1)
        self$`commonCropName` <- `commonCropName`
      }
      if (!missing(`countryOfOrigin`)) {
        stopifnot(is.character(`countryOfOrigin`), length(`countryOfOrigin`) == 1)
        self$`countryOfOrigin` <- `countryOfOrigin`
      }
      if (!missing(`defaultDisplayName`)) {
        stopifnot(is.character(`defaultDisplayName`), length(`defaultDisplayName`) == 1)
        self$`defaultDisplayName` <- `defaultDisplayName`
      }
      if (!missing(`documentationURL`)) {
        stopifnot(is.character(`documentationURL`), length(`documentationURL`) == 1)
        self$`documentationURL` <- `documentationURL`
      }
      if (!missing(`donors`)) {
        stopifnot(is.list(`donors`), length(`donors`) != 0)
        lapply(`donors`, function(x) stopifnot(is.character(x)))
        self$`donors` <- `donors`
      }
      if (!missing(`genus`)) {
        stopifnot(is.character(`genus`), length(`genus`) == 1)
        self$`genus` <- `genus`
      }
      if (!missing(`germplasmGenus`)) {
        stopifnot(is.character(`germplasmGenus`), length(`germplasmGenus`) == 1)
        self$`germplasmGenus` <- `germplasmGenus`
      }
      if (!missing(`germplasmDbId`)) {
        stopifnot(is.character(`germplasmDbId`), length(`germplasmDbId`) == 1)
        self$`germplasmDbId` <- `germplasmDbId`
      }
      if (!missing(`germplasmName`)) {
        stopifnot(is.character(`germplasmName`), length(`germplasmName`) == 1)
        self$`germplasmName` <- `germplasmName`
      }
      if (!missing(`germplasmPUI`)) {
        stopifnot(is.character(`germplasmPUI`), length(`germplasmPUI`) == 1)
        self$`germplasmPUI` <- `germplasmPUI`
      }
      if (!missing(`germplasmSpecies`)) {
        stopifnot(is.character(`germplasmSpecies`), length(`germplasmSpecies`) == 1)
        self$`germplasmSpecies` <- `germplasmSpecies`
      }
      if (!missing(`instituteCode`)) {
        stopifnot(is.character(`instituteCode`), length(`instituteCode`) == 1)
        self$`instituteCode` <- `instituteCode`
      }
      if (!missing(`instituteName`)) {
        stopifnot(is.character(`instituteName`), length(`instituteName`) == 1)
        self$`instituteName` <- `instituteName`
      }
      if (!missing(`pedigree`)) {
        stopifnot(is.character(`pedigree`), length(`pedigree`) == 1)
        self$`pedigree` <- `pedigree`
      }
      if (!missing(`seedsource`)) {
        stopifnot(is.character(`seedsource`), length(`seedsource`) == 1)
        self$`seedsource` <- `seedsource`
      }
      if (!missing(`species`)) {
        stopifnot(is.character(`species`), length(`species`) == 1)
        self$`species` <- `species`
      }
      if (!missing(`speciesAuthority`)) {
        stopifnot(is.character(`speciesAuthority`), length(`speciesAuthority`) == 1)
        self$`speciesAuthority` <- `speciesAuthority`
      }
      if (!missing(`subtaxa`)) {
        stopifnot(is.character(`subtaxa`), length(`subtaxa`) == 1)
        self$`subtaxa` <- `subtaxa`
      }
      if (!missing(`subtaxaAuthority`)) {
        stopifnot(is.character(`subtaxaAuthority`), length(`subtaxaAuthority`) == 1)
        self$`subtaxaAuthority` <- `subtaxaAuthority`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(is.character(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`taxonIds`)) {
        stopifnot(is.list(`taxonIds`), length(`taxonIds`) != 0)
        lapply(`taxonIds`, function(x) stopifnot(is.character(x)))
        self$`taxonIds` <- `taxonIds`
      }
      if (!missing(`typeOfGermplasmStorageCode`)) {
        stopifnot(is.list(`typeOfGermplasmStorageCode`), length(`typeOfGermplasmStorageCode`) != 0)
        lapply(`typeOfGermplasmStorageCode`, function(x) stopifnot(is.character(x)))
        self$`typeOfGermplasmStorageCode` <- `typeOfGermplasmStorageCode`
      }
    },
    toJSON = function() {
      BrapiGermplasmDTOObject <- list()
      if (!is.null(self$`accessionNumber`)) {
        BrapiGermplasmDTOObject[['accessionNumber']] <- self$`accessionNumber`
      }
      if (!is.null(self$`acquisitionDate`)) {
        BrapiGermplasmDTOObject[['acquisitionDate']] <- self$`acquisitionDate`
      }
      if (!is.null(self$`biologicalStatusOfAccessionCode`)) {
        BrapiGermplasmDTOObject[['biologicalStatusOfAccessionCode']] <- self$`biologicalStatusOfAccessionCode`
      }
      if (!is.null(self$`breedingMethodDbId`)) {
        BrapiGermplasmDTOObject[['breedingMethodDbId']] <- self$`breedingMethodDbId`
      }
      if (!is.null(self$`commonCropName`)) {
        BrapiGermplasmDTOObject[['commonCropName']] <- self$`commonCropName`
      }
      if (!is.null(self$`countryOfOrigin`)) {
        BrapiGermplasmDTOObject[['countryOfOrigin']] <- self$`countryOfOrigin`
      }
      if (!is.null(self$`defaultDisplayName`)) {
        BrapiGermplasmDTOObject[['defaultDisplayName']] <- self$`defaultDisplayName`
      }
      if (!is.null(self$`documentationURL`)) {
        BrapiGermplasmDTOObject[['documentationURL']] <- self$`documentationURL`
      }
      if (!is.null(self$`donors`)) {
        BrapiGermplasmDTOObject[['donors']] <- self$`donors`
      }
      if (!is.null(self$`genus`)) {
        BrapiGermplasmDTOObject[['genus']] <- self$`genus`
      }
      if (!is.null(self$`germplasmGenus`)) {
        BrapiGermplasmDTOObject[['germplasmGenus']] <- self$`germplasmGenus`
      }
      if (!is.null(self$`germplasmDbId`)) {
        BrapiGermplasmDTOObject[['germplasmDbId']] <- self$`germplasmDbId`
      }
      if (!is.null(self$`germplasmName`)) {
        BrapiGermplasmDTOObject[['germplasmName']] <- self$`germplasmName`
      }
      if (!is.null(self$`germplasmPUI`)) {
        BrapiGermplasmDTOObject[['germplasmPUI']] <- self$`germplasmPUI`
      }
      if (!is.null(self$`germplasmSpecies`)) {
        BrapiGermplasmDTOObject[['germplasmSpecies']] <- self$`germplasmSpecies`
      }
      if (!is.null(self$`instituteCode`)) {
        BrapiGermplasmDTOObject[['instituteCode']] <- self$`instituteCode`
      }
      if (!is.null(self$`instituteName`)) {
        BrapiGermplasmDTOObject[['instituteName']] <- self$`instituteName`
      }
      if (!is.null(self$`pedigree`)) {
        BrapiGermplasmDTOObject[['pedigree']] <- self$`pedigree`
      }
      if (!is.null(self$`seedsource`)) {
        BrapiGermplasmDTOObject[['seedsource']] <- self$`seedsource`
      }
      if (!is.null(self$`species`)) {
        BrapiGermplasmDTOObject[['species']] <- self$`species`
      }
      if (!is.null(self$`speciesAuthority`)) {
        BrapiGermplasmDTOObject[['speciesAuthority']] <- self$`speciesAuthority`
      }
      if (!is.null(self$`subtaxa`)) {
        BrapiGermplasmDTOObject[['subtaxa']] <- self$`subtaxa`
      }
      if (!is.null(self$`subtaxaAuthority`)) {
        BrapiGermplasmDTOObject[['subtaxaAuthority']] <- self$`subtaxaAuthority`
      }
      if (!is.null(self$`synonyms`)) {
        BrapiGermplasmDTOObject[['synonyms']] <- self$`synonyms`
      }
      if (!is.null(self$`taxonIds`)) {
        BrapiGermplasmDTOObject[['taxonIds']] <- self$`taxonIds`
      }
      if (!is.null(self$`typeOfGermplasmStorageCode`)) {
        BrapiGermplasmDTOObject[['typeOfGermplasmStorageCode']] <- self$`typeOfGermplasmStorageCode`
      }

      BrapiGermplasmDTOObject
    },
    fromJSON = function(BrapiGermplasmDTOJson) {
      BrapiGermplasmDTOObject <- jsonlite::fromJSON(BrapiGermplasmDTOJson)
      if (!is.null(BrapiGermplasmDTOObject$`accessionNumber`)) {
        self$`accessionNumber` <- BrapiGermplasmDTOObject$`accessionNumber`
      }
      if (!is.null(BrapiGermplasmDTOObject$`acquisitionDate`)) {
        self$`acquisitionDate` <- BrapiGermplasmDTOObject$`acquisitionDate`
      }
      if (!is.null(BrapiGermplasmDTOObject$`biologicalStatusOfAccessionCode`)) {
        self$`biologicalStatusOfAccessionCode` <- BrapiGermplasmDTOObject$`biologicalStatusOfAccessionCode`
      }
      if (!is.null(BrapiGermplasmDTOObject$`breedingMethodDbId`)) {
        self$`breedingMethodDbId` <- BrapiGermplasmDTOObject$`breedingMethodDbId`
      }
      if (!is.null(BrapiGermplasmDTOObject$`commonCropName`)) {
        self$`commonCropName` <- BrapiGermplasmDTOObject$`commonCropName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`countryOfOrigin`)) {
        self$`countryOfOrigin` <- BrapiGermplasmDTOObject$`countryOfOrigin`
      }
      if (!is.null(BrapiGermplasmDTOObject$`defaultDisplayName`)) {
        self$`defaultDisplayName` <- BrapiGermplasmDTOObject$`defaultDisplayName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`documentationURL`)) {
        self$`documentationURL` <- BrapiGermplasmDTOObject$`documentationURL`
      }
      if (!is.null(BrapiGermplasmDTOObject$`donors`)) {
        self$`donors` <- BrapiGermplasmDTOObject$`donors`
      }
      if (!is.null(BrapiGermplasmDTOObject$`genus`)) {
        self$`genus` <- BrapiGermplasmDTOObject$`genus`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmGenus`)) {
        self$`germplasmGenus` <- BrapiGermplasmDTOObject$`germplasmGenus`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmDbId`)) {
        self$`germplasmDbId` <- BrapiGermplasmDTOObject$`germplasmDbId`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmName`)) {
        self$`germplasmName` <- BrapiGermplasmDTOObject$`germplasmName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmPUI`)) {
        self$`germplasmPUI` <- BrapiGermplasmDTOObject$`germplasmPUI`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmSpecies`)) {
        self$`germplasmSpecies` <- BrapiGermplasmDTOObject$`germplasmSpecies`
      }
      if (!is.null(BrapiGermplasmDTOObject$`instituteCode`)) {
        self$`instituteCode` <- BrapiGermplasmDTOObject$`instituteCode`
      }
      if (!is.null(BrapiGermplasmDTOObject$`instituteName`)) {
        self$`instituteName` <- BrapiGermplasmDTOObject$`instituteName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`pedigree`)) {
        self$`pedigree` <- BrapiGermplasmDTOObject$`pedigree`
      }
      if (!is.null(BrapiGermplasmDTOObject$`seedsource`)) {
        self$`seedsource` <- BrapiGermplasmDTOObject$`seedsource`
      }
      if (!is.null(BrapiGermplasmDTOObject$`species`)) {
        self$`species` <- BrapiGermplasmDTOObject$`species`
      }
      if (!is.null(BrapiGermplasmDTOObject$`speciesAuthority`)) {
        self$`speciesAuthority` <- BrapiGermplasmDTOObject$`speciesAuthority`
      }
      if (!is.null(BrapiGermplasmDTOObject$`subtaxa`)) {
        self$`subtaxa` <- BrapiGermplasmDTOObject$`subtaxa`
      }
      if (!is.null(BrapiGermplasmDTOObject$`subtaxaAuthority`)) {
        self$`subtaxaAuthority` <- BrapiGermplasmDTOObject$`subtaxaAuthority`
      }
      if (!is.null(BrapiGermplasmDTOObject$`synonyms`)) {
        self$`synonyms` <- BrapiGermplasmDTOObject$`synonyms`
      }
      if (!is.null(BrapiGermplasmDTOObject$`taxonIds`)) {
        self$`taxonIds` <- BrapiGermplasmDTOObject$`taxonIds`
      }
      if (!is.null(BrapiGermplasmDTOObject$`typeOfGermplasmStorageCode`)) {
        self$`typeOfGermplasmStorageCode` <- BrapiGermplasmDTOObject$`typeOfGermplasmStorageCode`
      }
    },
    fromJSONObject = function(BrapiGermplasmDTOObject) {
      if (!is.null(BrapiGermplasmDTOObject$`accessionNumber`)) {
        self$`accessionNumber` <- BrapiGermplasmDTOObject$`accessionNumber`
      }
      if (!is.null(BrapiGermplasmDTOObject$`acquisitionDate`)) {
        self$`acquisitionDate` <- BrapiGermplasmDTOObject$`acquisitionDate`
      }
      if (!is.null(BrapiGermplasmDTOObject$`biologicalStatusOfAccessionCode`)) {
        self$`biologicalStatusOfAccessionCode` <- BrapiGermplasmDTOObject$`biologicalStatusOfAccessionCode`
      }
      if (!is.null(BrapiGermplasmDTOObject$`breedingMethodDbId`)) {
        self$`breedingMethodDbId` <- BrapiGermplasmDTOObject$`breedingMethodDbId`
      }
      if (!is.null(BrapiGermplasmDTOObject$`commonCropName`)) {
        self$`commonCropName` <- BrapiGermplasmDTOObject$`commonCropName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`countryOfOrigin`)) {
        self$`countryOfOrigin` <- BrapiGermplasmDTOObject$`countryOfOrigin`
      }
      if (!is.null(BrapiGermplasmDTOObject$`defaultDisplayName`)) {
        self$`defaultDisplayName` <- BrapiGermplasmDTOObject$`defaultDisplayName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`documentationURL`)) {
        self$`documentationURL` <- BrapiGermplasmDTOObject$`documentationURL`
      }
      if (!is.null(BrapiGermplasmDTOObject$`donors`)) {
        self$`donors` <- BrapiGermplasmDTOObject$`donors`
      }
      if (!is.null(BrapiGermplasmDTOObject$`genus`)) {
        self$`genus` <- BrapiGermplasmDTOObject$`genus`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmGenus`)) {
        self$`germplasmGenus` <- BrapiGermplasmDTOObject$`germplasmGenus`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmDbId`)) {
        self$`germplasmDbId` <- BrapiGermplasmDTOObject$`germplasmDbId`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmName`)) {
        self$`germplasmName` <- BrapiGermplasmDTOObject$`germplasmName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmPUI`)) {
        self$`germplasmPUI` <- BrapiGermplasmDTOObject$`germplasmPUI`
      }
      if (!is.null(BrapiGermplasmDTOObject$`germplasmSpecies`)) {
        self$`germplasmSpecies` <- BrapiGermplasmDTOObject$`germplasmSpecies`
      }
      if (!is.null(BrapiGermplasmDTOObject$`instituteCode`)) {
        self$`instituteCode` <- BrapiGermplasmDTOObject$`instituteCode`
      }
      if (!is.null(BrapiGermplasmDTOObject$`instituteName`)) {
        self$`instituteName` <- BrapiGermplasmDTOObject$`instituteName`
      }
      if (!is.null(BrapiGermplasmDTOObject$`pedigree`)) {
        self$`pedigree` <- BrapiGermplasmDTOObject$`pedigree`
      }
      if (!is.null(BrapiGermplasmDTOObject$`seedsource`)) {
        self$`seedsource` <- BrapiGermplasmDTOObject$`seedsource`
      }
      if (!is.null(BrapiGermplasmDTOObject$`species`)) {
        self$`species` <- BrapiGermplasmDTOObject$`species`
      }
      if (!is.null(BrapiGermplasmDTOObject$`speciesAuthority`)) {
        self$`speciesAuthority` <- BrapiGermplasmDTOObject$`speciesAuthority`
      }
      if (!is.null(BrapiGermplasmDTOObject$`subtaxa`)) {
        self$`subtaxa` <- BrapiGermplasmDTOObject$`subtaxa`
      }
      if (!is.null(BrapiGermplasmDTOObject$`subtaxaAuthority`)) {
        self$`subtaxaAuthority` <- BrapiGermplasmDTOObject$`subtaxaAuthority`
      }
      if (!is.null(BrapiGermplasmDTOObject$`synonyms`)) {
        self$`synonyms` <- BrapiGermplasmDTOObject$`synonyms`
      }
      if (!is.null(BrapiGermplasmDTOObject$`taxonIds`)) {
        self$`taxonIds` <- BrapiGermplasmDTOObject$`taxonIds`
      }
      if (!is.null(BrapiGermplasmDTOObject$`typeOfGermplasmStorageCode`)) {
        self$`typeOfGermplasmStorageCode` <- BrapiGermplasmDTOObject$`typeOfGermplasmStorageCode`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "accessionNumber": %s,
           "acquisitionDate": %s,
           "biologicalStatusOfAccessionCode": %s,
           "breedingMethodDbId": %s,
           "commonCropName": %s,
           "countryOfOrigin": %s,
           "defaultDisplayName": %s,
           "documentationURL": %s,
           "donors": [%s],
           "genus": %s,
           "germplasmGenus": %s,
           "germplasmDbId": %s,
           "germplasmName": %s,
           "germplasmPUI": %s,
           "germplasmSpecies": %s,
           "instituteCode": %s,
           "instituteName": %s,
           "pedigree": %s,
           "seedsource": %s,
           "species": %s,
           "speciesAuthority": %s,
           "subtaxa": %s,
           "subtaxaAuthority": %s,
           "synonyms": [%s],
           "taxonIds": [%s],
           "typeOfGermplasmStorageCode": [%s]
        }',
        jsonlite::toJSON(self$`accessionNumber`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`acquisitionDate`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`biologicalStatusOfAccessionCode`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`breedingMethodDbId`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`commonCropName`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`countryOfOrigin`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`defaultDisplayName`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`documentationURL`,auto_unbox=TRUE),
        lapply(self$`donors`, function(x) paste(paste0('"', x, '"'), sep=",")),
        jsonlite::toJSON(self$`genus`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`germplasmGenus`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`germplasmDbId`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`germplasmName`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`germplasmPUI`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`germplasmSpecies`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`instituteCode`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`instituteName`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`pedigree`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`seedsource`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`species`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`speciesAuthority`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`subtaxa`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`subtaxaAuthority`,auto_unbox=TRUE),
        lapply(self$`synonyms`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`taxonIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`typeOfGermplasmStorageCode`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(BrapiGermplasmDTOJson) {
      BrapiGermplasmDTOObject <- jsonlite::fromJSON(BrapiGermplasmDTOJson)
      self$`accessionNumber` <- BrapiGermplasmDTOObject$`accessionNumber`
      self$`acquisitionDate` <- BrapiGermplasmDTOObject$`acquisitionDate`
      self$`biologicalStatusOfAccessionCode` <- BrapiGermplasmDTOObject$`biologicalStatusOfAccessionCode`
      self$`breedingMethodDbId` <- BrapiGermplasmDTOObject$`breedingMethodDbId`
      self$`commonCropName` <- BrapiGermplasmDTOObject$`commonCropName`
      self$`countryOfOrigin` <- BrapiGermplasmDTOObject$`countryOfOrigin`
      self$`defaultDisplayName` <- BrapiGermplasmDTOObject$`defaultDisplayName`
      self$`documentationURL` <- BrapiGermplasmDTOObject$`documentationURL`
      self$`donors` <- BrapiGermplasmDTOObject$`donors`
      self$`genus` <- BrapiGermplasmDTOObject$`genus`
      self$`germplasmGenus` <- BrapiGermplasmDTOObject$`germplasmGenus`
      self$`germplasmDbId` <- BrapiGermplasmDTOObject$`germplasmDbId`
      self$`germplasmName` <- BrapiGermplasmDTOObject$`germplasmName`
      self$`germplasmPUI` <- BrapiGermplasmDTOObject$`germplasmPUI`
      self$`germplasmSpecies` <- BrapiGermplasmDTOObject$`germplasmSpecies`
      self$`instituteCode` <- BrapiGermplasmDTOObject$`instituteCode`
      self$`instituteName` <- BrapiGermplasmDTOObject$`instituteName`
      self$`pedigree` <- BrapiGermplasmDTOObject$`pedigree`
      self$`seedsource` <- BrapiGermplasmDTOObject$`seedsource`
      self$`species` <- BrapiGermplasmDTOObject$`species`
      self$`speciesAuthority` <- BrapiGermplasmDTOObject$`speciesAuthority`
      self$`subtaxa` <- BrapiGermplasmDTOObject$`subtaxa`
      self$`subtaxaAuthority` <- BrapiGermplasmDTOObject$`subtaxaAuthority`
      self$`synonyms` <- BrapiGermplasmDTOObject$`synonyms`
      self$`taxonIds` <- BrapiGermplasmDTOObject$`taxonIds`
      self$`typeOfGermplasmStorageCode` <- BrapiGermplasmDTOObject$`typeOfGermplasmStorageCode`
    }
  )
)
