# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0.2
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ConcernedItemDTO Class
#'
#' @field uri 
#' @field typeURI 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConcernedItemDTO <- R6::R6Class(
  'ConcernedItemDTO',
  public = list(
    `uri` = NULL,
    `typeURI` = NULL,
    initialize = function(`uri`, `typeURI`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`typeURI`)) {
        stopifnot(is.character(`typeURI`), length(`typeURI`) == 1)
        self$`typeURI` <- `typeURI`
      }
    },
    toJSON = function() {
      ConcernedItemDTOObject <- list()
      if (!is.null(self$`uri`)) {
        ConcernedItemDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`typeURI`)) {
        ConcernedItemDTOObject[['typeURI']] <- self$`typeURI`
      }

      ConcernedItemDTOObject
    },
    fromJSON = function(ConcernedItemDTOJson) {
      ConcernedItemDTOObject <- jsonlite::fromJSON(ConcernedItemDTOJson)
      if (!is.null(ConcernedItemDTOObject$`uri`)) {
        self$`uri` <- ConcernedItemDTOObject$`uri`
      }
      if (!is.null(ConcernedItemDTOObject$`typeURI`)) {
        self$`typeURI` <- ConcernedItemDTOObject$`typeURI`
      }
    },
    fromJSONObject = function(ConcernedItemDTOObject) {
      if (!is.null(ConcernedItemDTOObject$`uri`)) {
        self$`uri` <- ConcernedItemDTOObject$`uri`
      }
      if (!is.null(ConcernedItemDTOObject$`typeURI`)) {
        self$`typeURI` <- ConcernedItemDTOObject$`typeURI`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "typeURI": %s
        }',
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`typeURI`,auto_unbox=TRUE)
      )
    },
    fromJSONString = function(ConcernedItemDTOJson) {
      ConcernedItemDTOObject <- jsonlite::fromJSON(ConcernedItemDTOJson)
      self$`uri` <- ConcernedItemDTOObject$`uri`
      self$`typeURI` <- ConcernedItemDTOObject$`typeURI`
    }
  )
)
