# openSilexTestAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FactorDTO Class
#'
#' @field uri 
#' @field label 
#' @field comment 
#' @field ontologiesReferences 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FactorDTO <- R6::R6Class(
  'FactorDTO',
  public = list(
    `uri` = NULL,
    `label` = NULL,
    `comment` = NULL,
    `ontologiesReferences` = NULL,
    initialize = function(`uri`, `label`, `comment`, `ontologiesReferences`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`comment`)) {
        stopifnot(is.character(`comment`), length(`comment`) == 1)
        self$`comment` <- `comment`
      }
      if (!missing(`ontologiesReferences`)) {
        stopifnot(is.list(`ontologiesReferences`), length(`ontologiesReferences`) != 0)
        lapply(`ontologiesReferences`, function(x) stopifnot(R6::is.R6(x)))
        self$`ontologiesReferences` <- `ontologiesReferences`
      }
    },
    toJSON = function() {
      FactorDTOObject <- list()
      if (!is.null(self$`uri`)) {
        FactorDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`label`)) {
        FactorDTOObject[['label']] <- self$`label`
      }
      if (!is.null(self$`comment`)) {
        FactorDTOObject[['comment']] <- self$`comment`
      }
      if (!is.null(self$`ontologiesReferences`)) {
        FactorDTOObject[['ontologiesReferences']] <- lapply(self$`ontologiesReferences`, function(x) x$toJSON())
      }

      FactorDTOObject
    },
    fromJSON = function(FactorDTOJson) {
      FactorDTOObject <- jsonlite::fromJSON(FactorDTOJson)
      if (!is.null(FactorDTOObject$`uri`)) {
        self$`uri` <- FactorDTOObject$`uri`
      }
      if (!is.null(FactorDTOObject$`label`)) {
        self$`label` <- FactorDTOObject$`label`
      }
      if (!is.null(FactorDTOObject$`comment`)) {
        self$`comment` <- FactorDTOObject$`comment`
      }
      if (!is.null(FactorDTOObject$`ontologiesReferences`)) {
        self$`ontologiesReferences` <- lapply(FactorDTOObject$`ontologiesReferences`, function(x) {
          ontologiesReferencesObject <- OntologyReference$new()
          ontologiesReferencesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          ontologiesReferencesObject
        })
      }
    },
    fromJSONObject = function(FactorDTOObject) {
      if (!is.null(FactorDTOObject$`uri`)) {
        self$`uri` <- FactorDTOObject$`uri`
      }
      if (!is.null(FactorDTOObject$`label`)) {
        self$`label` <- FactorDTOObject$`label`
      }
      if (!is.null(FactorDTOObject$`comment`)) {
        self$`comment` <- FactorDTOObject$`comment`
      }
      if (!is.null(FactorDTOObject$`ontologiesReferences`)) {
        self$`ontologiesReferences` <- lapply(FactorDTOObject$`ontologiesReferences`, function(x) {
          ontologiesReferencesObject <- OntologyReference$new()
          ontologiesReferencesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          ontologiesReferencesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "label": %s,
           "comment": %s,
           "ontologiesReferences": [%s]
        }',
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`label`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`comment`,auto_unbox=TRUE),
        lapply(self$`ontologiesReferences`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(FactorDTOJson) {
      FactorDTOObject <- jsonlite::fromJSON(FactorDTOJson)
      self$`uri` <- FactorDTOObject$`uri`
      self$`label` <- FactorDTOObject$`label`
      self$`comment` <- FactorDTOObject$`comment`
      self$`ontologiesReferences` <- lapply(FactorDTOObject$`ontologiesReferences`, function(x) OntologyReference$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
