# openSilexTestAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GermplasmPostDTO Class
#'
#' @field rdfType 
#' @field label 
#' @field properties 
#' @field uri 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GermplasmPostDTO <- R6::R6Class(
  'GermplasmPostDTO',
  public = list(
    `rdfType` = NULL,
    `label` = NULL,
    `properties` = NULL,
    `uri` = NULL,
    initialize = function(`rdfType`, `label`, `properties`, `uri`){
      if (!missing(`rdfType`)) {
        stopifnot(is.character(`rdfType`), length(`rdfType`) == 1)
        self$`rdfType` <- `rdfType`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`properties`)) {
        stopifnot(is.list(`properties`), length(`properties`) != 0)
        lapply(`properties`, function(x) stopifnot(R6::is.R6(x)))
        self$`properties` <- `properties`
      }
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
    },
    toJSON = function() {
      GermplasmPostDTOObject <- list()
      if (!is.null(self$`rdfType`)) {
        GermplasmPostDTOObject[['rdfType']] <- self$`rdfType`
      }
      if (!is.null(self$`label`)) {
        GermplasmPostDTOObject[['label']] <- self$`label`
      }
      if (!is.null(self$`properties`)) {
        GermplasmPostDTOObject[['properties']] <- lapply(self$`properties`, function(x) x$toJSON())
      }
      if (!is.null(self$`uri`)) {
        GermplasmPostDTOObject[['uri']] <- self$`uri`
      }

      GermplasmPostDTOObject
    },
    fromJSON = function(GermplasmPostDTOJson) {
      GermplasmPostDTOObject <- jsonlite::fromJSON(GermplasmPostDTOJson)
      if (!is.null(GermplasmPostDTOObject$`rdfType`)) {
        self$`rdfType` <- GermplasmPostDTOObject$`rdfType`
      }
      if (!is.null(GermplasmPostDTOObject$`label`)) {
        self$`label` <- GermplasmPostDTOObject$`label`
      }
      if (!is.null(GermplasmPostDTOObject$`properties`)) {
        self$`properties` <- lapply(GermplasmPostDTOObject$`properties`, function(x) {
          propertiesObject <- PropertyPostDTO$new()
          propertiesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          propertiesObject
        })
      }
      if (!is.null(GermplasmPostDTOObject$`uri`)) {
        self$`uri` <- GermplasmPostDTOObject$`uri`
      }
    },
    fromJSONObject = function(GermplasmPostDTOObject) {
      if (!is.null(GermplasmPostDTOObject$`rdfType`)) {
        self$`rdfType` <- GermplasmPostDTOObject$`rdfType`
      }
      if (!is.null(GermplasmPostDTOObject$`label`)) {
        self$`label` <- GermplasmPostDTOObject$`label`
      }
      if (!is.null(GermplasmPostDTOObject$`properties`)) {
        self$`properties` <- lapply(GermplasmPostDTOObject$`properties`, function(x) {
          propertiesObject <- PropertyPostDTO$new()
          propertiesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          propertiesObject
        })
      }
      if (!is.null(GermplasmPostDTOObject$`uri`)) {
        self$`uri` <- GermplasmPostDTOObject$`uri`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "rdfType": %s,
           "label": %s,
           "properties": [%s],
           "uri": %s
        }',
        jsonlite::toJSON(self$`rdfType`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`label`,auto_unbox=TRUE),
        lapply(self$`properties`, function(x) paste(x$toJSON(), sep=",")),
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE)
      )
    },
    fromJSONString = function(GermplasmPostDTOJson) {
      GermplasmPostDTOObject <- jsonlite::fromJSON(GermplasmPostDTOJson)
      self$`rdfType` <- GermplasmPostDTOObject$`rdfType`
      self$`label` <- GermplasmPostDTOObject$`label`
      self$`properties` <- lapply(GermplasmPostDTOObject$`properties`, function(x) PropertyPostDTO$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`uri` <- GermplasmPostDTOObject$`uri`
    }
  )
)
