# openSilexTestAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JsonNull Class
#'
#' @field asString 
#' @field asJsonArray 
#' @field asJsonPrimitive 
#' @field asJsonObject 
#' @field jsonObject 
#' @field jsonPrimitive 
#' @field jsonNull 
#' @field jsonArray 
#' @field asJsonNull 
#' @field asNumber 
#' @field asFloat 
#' @field asByte 
#' @field asCharacter 
#' @field asBigDecimal 
#' @field asBigInteger 
#' @field asShort 
#' @field asBoolean 
#' @field asInt 
#' @field asDouble 
#' @field asLong 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JsonNull <- R6::R6Class(
  'JsonNull',
  public = list(
    `asString` = NULL,
    `asJsonArray` = NULL,
    `asJsonPrimitive` = NULL,
    `asJsonObject` = NULL,
    `jsonObject` = NULL,
    `jsonPrimitive` = NULL,
    `jsonNull` = NULL,
    `jsonArray` = NULL,
    `asJsonNull` = NULL,
    `asNumber` = NULL,
    `asFloat` = NULL,
    `asByte` = NULL,
    `asCharacter` = NULL,
    `asBigDecimal` = NULL,
    `asBigInteger` = NULL,
    `asShort` = NULL,
    `asBoolean` = NULL,
    `asInt` = NULL,
    `asDouble` = NULL,
    `asLong` = NULL,
    initialize = function(`asString`, `asJsonArray`, `asJsonPrimitive`, `asJsonObject`, `jsonObject`, `jsonPrimitive`, `jsonNull`, `jsonArray`, `asJsonNull`, `asNumber`, `asFloat`, `asByte`, `asCharacter`, `asBigDecimal`, `asBigInteger`, `asShort`, `asBoolean`, `asInt`, `asDouble`, `asLong`){
      if (!missing(`asString`)) {
        stopifnot(is.character(`asString`), length(`asString`) == 1)
        self$`asString` <- `asString`
      }
      if (!missing(`asJsonArray`)) {
        stopifnot(R6::is.R6(`asJsonArray`))
        self$`asJsonArray` <- `asJsonArray`
      }
      if (!missing(`asJsonPrimitive`)) {
        stopifnot(R6::is.R6(`asJsonPrimitive`))
        self$`asJsonPrimitive` <- `asJsonPrimitive`
      }
      if (!missing(`asJsonObject`)) {
        stopifnot(R6::is.R6(`asJsonObject`))
        self$`asJsonObject` <- `asJsonObject`
      }
      if (!missing(`jsonObject`)) {
        self$`jsonObject` <- `jsonObject`
      }
      if (!missing(`jsonPrimitive`)) {
        self$`jsonPrimitive` <- `jsonPrimitive`
      }
      if (!missing(`jsonNull`)) {
        self$`jsonNull` <- `jsonNull`
      }
      if (!missing(`jsonArray`)) {
        self$`jsonArray` <- `jsonArray`
      }
      if (!missing(`asJsonNull`)) {
        stopifnot(R6::is.R6(`asJsonNull`))
        self$`asJsonNull` <- `asJsonNull`
      }
      if (!missing(`asNumber`)) {
        stopifnot(R6::is.R6(`asNumber`))
        self$`asNumber` <- `asNumber`
      }
      if (!missing(`asFloat`)) {
        stopifnot(is.numeric(`asFloat`), length(`asFloat`) == 1)
        self$`asFloat` <- `asFloat`
      }
      if (!missing(`asByte`)) {
        stopifnot(is.character(`asByte`), length(`asByte`) == 1)
        self$`asByte` <- `asByte`
      }
      if (!missing(`asCharacter`)) {
        stopifnot(is.character(`asCharacter`), length(`asCharacter`) == 1)
        self$`asCharacter` <- `asCharacter`
      }
      if (!missing(`asBigDecimal`)) {
        self$`asBigDecimal` <- `asBigDecimal`
      }
      if (!missing(`asBigInteger`)) {
        stopifnot(is.numeric(`asBigInteger`), length(`asBigInteger`) == 1)
        self$`asBigInteger` <- `asBigInteger`
      }
      if (!missing(`asShort`)) {
        stopifnot(is.numeric(`asShort`), length(`asShort`) == 1)
        self$`asShort` <- `asShort`
      }
      if (!missing(`asBoolean`)) {
        self$`asBoolean` <- `asBoolean`
      }
      if (!missing(`asInt`)) {
        stopifnot(is.numeric(`asInt`), length(`asInt`) == 1)
        self$`asInt` <- `asInt`
      }
      if (!missing(`asDouble`)) {
        stopifnot(is.numeric(`asDouble`), length(`asDouble`) == 1)
        self$`asDouble` <- `asDouble`
      }
      if (!missing(`asLong`)) {
        stopifnot(is.numeric(`asLong`), length(`asLong`) == 1)
        self$`asLong` <- `asLong`
      }
    },
    toJSON = function() {
      JsonNullObject <- list()
      if (!is.null(self$`asString`)) {
        JsonNullObject[['asString']] <- self$`asString`
      }
      if (!is.null(self$`asJsonArray`)) {
        JsonNullObject[['asJsonArray']] <- self$`asJsonArray`$toJSON()
      }
      if (!is.null(self$`asJsonPrimitive`)) {
        JsonNullObject[['asJsonPrimitive']] <- self$`asJsonPrimitive`$toJSON()
      }
      if (!is.null(self$`asJsonObject`)) {
        JsonNullObject[['asJsonObject']] <- self$`asJsonObject`$toJSON()
      }
      if (!is.null(self$`jsonObject`)) {
        JsonNullObject[['jsonObject']] <- self$`jsonObject`
      }
      if (!is.null(self$`jsonPrimitive`)) {
        JsonNullObject[['jsonPrimitive']] <- self$`jsonPrimitive`
      }
      if (!is.null(self$`jsonNull`)) {
        JsonNullObject[['jsonNull']] <- self$`jsonNull`
      }
      if (!is.null(self$`jsonArray`)) {
        JsonNullObject[['jsonArray']] <- self$`jsonArray`
      }
      if (!is.null(self$`asJsonNull`)) {
        JsonNullObject[['asJsonNull']] <- self$`asJsonNull`$toJSON()
      }
      if (!is.null(self$`asNumber`)) {
        JsonNullObject[['asNumber']] <- self$`asNumber`$toJSON()
      }
      if (!is.null(self$`asFloat`)) {
        JsonNullObject[['asFloat']] <- self$`asFloat`
      }
      if (!is.null(self$`asByte`)) {
        JsonNullObject[['asByte']] <- self$`asByte`
      }
      if (!is.null(self$`asCharacter`)) {
        JsonNullObject[['asCharacter']] <- self$`asCharacter`
      }
      if (!is.null(self$`asBigDecimal`)) {
        JsonNullObject[['asBigDecimal']] <- self$`asBigDecimal`
      }
      if (!is.null(self$`asBigInteger`)) {
        JsonNullObject[['asBigInteger']] <- self$`asBigInteger`
      }
      if (!is.null(self$`asShort`)) {
        JsonNullObject[['asShort']] <- self$`asShort`
      }
      if (!is.null(self$`asBoolean`)) {
        JsonNullObject[['asBoolean']] <- self$`asBoolean`
      }
      if (!is.null(self$`asInt`)) {
        JsonNullObject[['asInt']] <- self$`asInt`
      }
      if (!is.null(self$`asDouble`)) {
        JsonNullObject[['asDouble']] <- self$`asDouble`
      }
      if (!is.null(self$`asLong`)) {
        JsonNullObject[['asLong']] <- self$`asLong`
      }

      JsonNullObject
    },
    fromJSON = function(JsonNullJson) {
      JsonNullObject <- jsonlite::fromJSON(JsonNullJson)
      if (!is.null(JsonNullObject$`asString`)) {
        self$`asString` <- JsonNullObject$`asString`
      }
      if (!is.null(JsonNullObject$`asJsonArray`)) {
        asJsonArrayObject <- JsonArray$new()
        asJsonArrayObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonArray, auto_unbox = TRUE))
        self$`asJsonArray` <- asJsonArrayObject
      }
      if (!is.null(JsonNullObject$`asJsonPrimitive`)) {
        asJsonPrimitiveObject <- JsonPrimitive$new()
        asJsonPrimitiveObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonPrimitive, auto_unbox = TRUE))
        self$`asJsonPrimitive` <- asJsonPrimitiveObject
      }
      if (!is.null(JsonNullObject$`asJsonObject`)) {
        asJsonObjectObject <- JsonObject$new()
        asJsonObjectObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonObject, auto_unbox = TRUE))
        self$`asJsonObject` <- asJsonObjectObject
      }
      if (!is.null(JsonNullObject$`jsonObject`)) {
        self$`jsonObject` <- JsonNullObject$`jsonObject`
      }
      if (!is.null(JsonNullObject$`jsonPrimitive`)) {
        self$`jsonPrimitive` <- JsonNullObject$`jsonPrimitive`
      }
      if (!is.null(JsonNullObject$`jsonNull`)) {
        self$`jsonNull` <- JsonNullObject$`jsonNull`
      }
      if (!is.null(JsonNullObject$`jsonArray`)) {
        self$`jsonArray` <- JsonNullObject$`jsonArray`
      }
      if (!is.null(JsonNullObject$`asJsonNull`)) {
        asJsonNullObject <- JsonNull$new()
        asJsonNullObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonNull, auto_unbox = TRUE))
        self$`asJsonNull` <- asJsonNullObject
      }
      if (!is.null(JsonNullObject$`asNumber`)) {
        asNumberObject <- Number$new()
        asNumberObject$fromJSON(jsonlite::toJSON(JsonNullObject$asNumber, auto_unbox = TRUE))
        self$`asNumber` <- asNumberObject
      }
      if (!is.null(JsonNullObject$`asFloat`)) {
        self$`asFloat` <- JsonNullObject$`asFloat`
      }
      if (!is.null(JsonNullObject$`asByte`)) {
        self$`asByte` <- JsonNullObject$`asByte`
      }
      if (!is.null(JsonNullObject$`asCharacter`)) {
        self$`asCharacter` <- JsonNullObject$`asCharacter`
      }
      if (!is.null(JsonNullObject$`asBigDecimal`)) {
        self$`asBigDecimal` <- JsonNullObject$`asBigDecimal`
      }
      if (!is.null(JsonNullObject$`asBigInteger`)) {
        self$`asBigInteger` <- JsonNullObject$`asBigInteger`
      }
      if (!is.null(JsonNullObject$`asShort`)) {
        self$`asShort` <- JsonNullObject$`asShort`
      }
      if (!is.null(JsonNullObject$`asBoolean`)) {
        self$`asBoolean` <- JsonNullObject$`asBoolean`
      }
      if (!is.null(JsonNullObject$`asInt`)) {
        self$`asInt` <- JsonNullObject$`asInt`
      }
      if (!is.null(JsonNullObject$`asDouble`)) {
        self$`asDouble` <- JsonNullObject$`asDouble`
      }
      if (!is.null(JsonNullObject$`asLong`)) {
        self$`asLong` <- JsonNullObject$`asLong`
      }
    },
    fromJSONObject = function(JsonNullObject) {
      if (!is.null(JsonNullObject$`asString`)) {
        self$`asString` <- JsonNullObject$`asString`
      }
      if (!is.null(JsonNullObject$`asJsonArray`)) {
        asJsonArrayObject <- JsonArray$new()
        asJsonArrayObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonArray, auto_unbox = TRUE))
        self$`asJsonArray` <- asJsonArrayObject
      }
      if (!is.null(JsonNullObject$`asJsonPrimitive`)) {
        asJsonPrimitiveObject <- JsonPrimitive$new()
        asJsonPrimitiveObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonPrimitive, auto_unbox = TRUE))
        self$`asJsonPrimitive` <- asJsonPrimitiveObject
      }
      if (!is.null(JsonNullObject$`asJsonObject`)) {
        asJsonObjectObject <- JsonObject$new()
        asJsonObjectObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonObject, auto_unbox = TRUE))
        self$`asJsonObject` <- asJsonObjectObject
      }
      if (!is.null(JsonNullObject$`jsonObject`)) {
        self$`jsonObject` <- JsonNullObject$`jsonObject`
      }
      if (!is.null(JsonNullObject$`jsonPrimitive`)) {
        self$`jsonPrimitive` <- JsonNullObject$`jsonPrimitive`
      }
      if (!is.null(JsonNullObject$`jsonNull`)) {
        self$`jsonNull` <- JsonNullObject$`jsonNull`
      }
      if (!is.null(JsonNullObject$`jsonArray`)) {
        self$`jsonArray` <- JsonNullObject$`jsonArray`
      }
      if (!is.null(JsonNullObject$`asJsonNull`)) {
        asJsonNullObject <- JsonNull$new()
        asJsonNullObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonNull, auto_unbox = TRUE))
        self$`asJsonNull` <- asJsonNullObject
      }
      if (!is.null(JsonNullObject$`asNumber`)) {
        asNumberObject <- Number$new()
        asNumberObject$fromJSON(jsonlite::toJSON(JsonNullObject$asNumber, auto_unbox = TRUE))
        self$`asNumber` <- asNumberObject
      }
      if (!is.null(JsonNullObject$`asFloat`)) {
        self$`asFloat` <- JsonNullObject$`asFloat`
      }
      if (!is.null(JsonNullObject$`asByte`)) {
        self$`asByte` <- JsonNullObject$`asByte`
      }
      if (!is.null(JsonNullObject$`asCharacter`)) {
        self$`asCharacter` <- JsonNullObject$`asCharacter`
      }
      if (!is.null(JsonNullObject$`asBigDecimal`)) {
        self$`asBigDecimal` <- JsonNullObject$`asBigDecimal`
      }
      if (!is.null(JsonNullObject$`asBigInteger`)) {
        self$`asBigInteger` <- JsonNullObject$`asBigInteger`
      }
      if (!is.null(JsonNullObject$`asShort`)) {
        self$`asShort` <- JsonNullObject$`asShort`
      }
      if (!is.null(JsonNullObject$`asBoolean`)) {
        self$`asBoolean` <- JsonNullObject$`asBoolean`
      }
      if (!is.null(JsonNullObject$`asInt`)) {
        self$`asInt` <- JsonNullObject$`asInt`
      }
      if (!is.null(JsonNullObject$`asDouble`)) {
        self$`asDouble` <- JsonNullObject$`asDouble`
      }
      if (!is.null(JsonNullObject$`asLong`)) {
        self$`asLong` <- JsonNullObject$`asLong`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "asString": %s,
           "asJsonArray": %s,
           "asJsonPrimitive": %s,
           "asJsonObject": %s,
           "jsonObject": %s,
           "jsonPrimitive": %s,
           "jsonNull": %s,
           "jsonArray": %s,
           "asJsonNull": %s,
           "asNumber": %s,
           "asFloat": %d,
           "asByte": %s,
           "asCharacter": %s,
           "asBigDecimal": %s,
           "asBigInteger": %d,
           "asShort": %s,
           "asBoolean": %s,
           "asInt": %s,
           "asDouble": %d,
           "asLong": %d
        }',
        jsonlite::toJSON(self$`asString`,auto_unbox=TRUE),
        self$`asJsonArray`$toJSON(),
        self$`asJsonPrimitive`$toJSON(),
        self$`asJsonObject`$toJSON(),
        jsonlite::toJSON(self$`jsonObject`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`jsonPrimitive`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`jsonNull`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`jsonArray`,auto_unbox=TRUE),
        self$`asJsonNull`$toJSON(),
        self$`asNumber`$toJSON(),
        jsonlite::toJSON(self$`asFloat`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asByte`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asCharacter`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asBigDecimal`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asBigInteger`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asShort`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asBoolean`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asInt`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asDouble`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`asLong`,auto_unbox=TRUE)
      )
    },
    fromJSONString = function(JsonNullJson) {
      JsonNullObject <- jsonlite::fromJSON(JsonNullJson)
      self$`asString` <- JsonNullObject$`asString`
      JsonArrayObject <- JsonArray$new()
      self$`asJsonArray` <- JsonArrayObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonArray, auto_unbox = TRUE))
      JsonPrimitiveObject <- JsonPrimitive$new()
      self$`asJsonPrimitive` <- JsonPrimitiveObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonPrimitive, auto_unbox = TRUE))
      JsonObjectObject <- JsonObject$new()
      self$`asJsonObject` <- JsonObjectObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonObject, auto_unbox = TRUE))
      self$`jsonObject` <- JsonNullObject$`jsonObject`
      self$`jsonPrimitive` <- JsonNullObject$`jsonPrimitive`
      self$`jsonNull` <- JsonNullObject$`jsonNull`
      self$`jsonArray` <- JsonNullObject$`jsonArray`
      JsonNullObject <- JsonNull$new()
      self$`asJsonNull` <- JsonNullObject$fromJSON(jsonlite::toJSON(JsonNullObject$asJsonNull, auto_unbox = TRUE))
      NumberObject <- Number$new()
      self$`asNumber` <- NumberObject$fromJSON(jsonlite::toJSON(JsonNullObject$asNumber, auto_unbox = TRUE))
      self$`asFloat` <- JsonNullObject$`asFloat`
      self$`asByte` <- JsonNullObject$`asByte`
      self$`asCharacter` <- JsonNullObject$`asCharacter`
      self$`asBigDecimal` <- JsonNullObject$`asBigDecimal`
      self$`asBigInteger` <- JsonNullObject$`asBigInteger`
      self$`asShort` <- JsonNullObject$`asShort`
      self$`asBoolean` <- JsonNullObject$`asBoolean`
      self$`asInt` <- JsonNullObject$`asInt`
      self$`asDouble` <- JsonNullObject$`asDouble`
      self$`asLong` <- JsonNullObject$`asLong`
    }
  )
)
