# openSilexTestAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Number Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Number <- R6::R6Class(
  'Number',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      NumberObject <- list()

      NumberObject
    },
    fromJSON = function(NumberJson) {
      NumberObject <- jsonlite::fromJSON(NumberJson)
    },
    fromJSONObject = function(NumberObject) {
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(NumberJson) {
      NumberObject <- jsonlite::fromJSON(NumberJson)
    }
  )
)
