# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0.2
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ProvenancePostDTO Class
#'
#' @field label 
#' @field comment 
#' @field metadata 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProvenancePostDTO <- R6::R6Class(
  'ProvenancePostDTO',
  public = list(
    `label` = NULL,
    `comment` = NULL,
    `metadata` = NULL,
    initialize = function(`label`, `comment`, `metadata`){
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`comment`)) {
        stopifnot(is.character(`comment`), length(`comment`) == 1)
        self$`comment` <- `comment`
      }
      if (!missing(`metadata`)) {
        stopifnot(R6::is.R6(`metadata`))
        self$`metadata` <- `metadata`
      }
    },
    toJSON = function() {
      ProvenancePostDTOObject <- list()
      if (!is.null(self$`label`)) {
        ProvenancePostDTOObject[['label']] <- self$`label`
      }
      if (!is.null(self$`comment`)) {
        ProvenancePostDTOObject[['comment']] <- self$`comment`
      }
      if (!is.null(self$`metadata`)) {
        ProvenancePostDTOObject[['metadata']] <- self$`metadata`$toJSON()
      }

      ProvenancePostDTOObject
    },
    fromJSON = function(ProvenancePostDTOJson) {
      ProvenancePostDTOObject <- jsonlite::fromJSON(ProvenancePostDTOJson)
      if (!is.null(ProvenancePostDTOObject$`label`)) {
        self$`label` <- ProvenancePostDTOObject$`label`
      }
      if (!is.null(ProvenancePostDTOObject$`comment`)) {
        self$`comment` <- ProvenancePostDTOObject$`comment`
      }
      if (!is.null(ProvenancePostDTOObject$`metadata`)) {
        metadataObject <- TODO_OBJECT_MAPPING$new()
        metadataObject$fromJSON(jsonlite::toJSON(ProvenancePostDTOObject$metadata, auto_unbox = TRUE))
        self$`metadata` <- metadataObject
      }
    },
    fromJSONObject = function(ProvenancePostDTOObject) {
      if (!is.null(ProvenancePostDTOObject$`label`)) {
        self$`label` <- ProvenancePostDTOObject$`label`
      }
      if (!is.null(ProvenancePostDTOObject$`comment`)) {
        self$`comment` <- ProvenancePostDTOObject$`comment`
      }
      if (!is.null(ProvenancePostDTOObject$`metadata`)) {
        metadataObject <- TODO_OBJECT_MAPPING$new()
        metadataObject$fromJSON(jsonlite::toJSON(ProvenancePostDTOObject$metadata, auto_unbox = TRUE))
        self$`metadata` <- metadataObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "label": %s,
           "comment": %s,
           "metadata": %s
        }',
        jsonlite::toJSON(self$`label`,auto_unbox=TRUE),
        jsonlite::toJSON(self$`comment`,auto_unbox=TRUE),
        self$`metadata`$toJSON()
      )
    },
    fromJSONString = function(ProvenancePostDTOJson) {
      ProvenancePostDTOObject <- jsonlite::fromJSON(ProvenancePostDTOJson)
      self$`label` <- ProvenancePostDTOObject$`label`
      self$`comment` <- ProvenancePostDTOObject$`comment`
      TODO_OBJECT_MAPPINGObject <- TODO_OBJECT_MAPPING$new()
      self$`metadata` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(ProvenancePostDTOObject$metadata, auto_unbox = TRUE))
    }
  )
)
