# sunagriAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' RdfResourceDefinitionDTO Class
#'
#' @field uri 
#' @field label 
#' @field properties 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RdfResourceDefinitionDTO <- R6::R6Class(
  'RdfResourceDefinitionDTO',
  public = list(
    `uri` = NULL,
    `label` = NULL,
    `properties` = NULL,
    initialize = function(`uri`, `label`, `properties`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`properties`)) {
        stopifnot(is.list(`properties`), length(`properties`) != 0)
        lapply(`properties`, function(x) stopifnot(R6::is.R6(x)))
        self$`properties` <- `properties`
      }
    },
    toJSON = function() {
      RdfResourceDefinitionDTOObject <- list()
      if (!is.null(self$`uri`)) {
        RdfResourceDefinitionDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`label`)) {
        RdfResourceDefinitionDTOObject[['label']] <- self$`label`
      }
      if (!is.null(self$`properties`)) {
        RdfResourceDefinitionDTOObject[['properties']] <- lapply(self$`properties`, function(x) x$toJSON())
      }

      RdfResourceDefinitionDTOObject
    },
    fromJSON = function(RdfResourceDefinitionDTOJson) {
      RdfResourceDefinitionDTOObject <- jsonlite::fromJSON(RdfResourceDefinitionDTOJson)
      if (!is.null(RdfResourceDefinitionDTOObject$`uri`)) {
        self$`uri` <- RdfResourceDefinitionDTOObject$`uri`
      }
      if (!is.null(RdfResourceDefinitionDTOObject$`label`)) {
        self$`label` <- RdfResourceDefinitionDTOObject$`label`
      }
      if (!is.null(RdfResourceDefinitionDTOObject$`properties`)) {
        self$`properties` <- lapply(RdfResourceDefinitionDTOObject$`properties`, function(x) {
          propertiesObject <- PropertyDTO$new()
          propertiesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE, null = "null"))
          propertiesObject
        })
      }
    },
    fromJSONObject = function(RdfResourceDefinitionDTOObject) {
      if (!is.null(RdfResourceDefinitionDTOObject$`uri`)) {
        self$`uri` <- RdfResourceDefinitionDTOObject$`uri`
      }
      if (!is.null(RdfResourceDefinitionDTOObject$`label`)) {
        self$`label` <- RdfResourceDefinitionDTOObject$`label`
      }
      if (!is.null(RdfResourceDefinitionDTOObject$`properties`)) {
        self$`properties` <- lapply(RdfResourceDefinitionDTOObject$`properties`, function(x) {
          propertiesObject <- PropertyDTO$new()
          propertiesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE, null = "null"))
          propertiesObject
        })
      }
    },
    toJSONString = function() {
      propertiesList = paste(lapply(self$`properties`, function(x) x$toJSONString()),collapse = ",")
       sprintf(
        '{
           "uri": %s,
           "label": %s,
           "properties": [%s]
        }',
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`label`,auto_unbox=TRUE, null = "null"),
        propertiesList
      )
    },
    fromJSONString = function(RdfResourceDefinitionDTOJson) {
      RdfResourceDefinitionDTOObject <- jsonlite::fromJSON(RdfResourceDefinitionDTOJson)
      self$`uri` <- RdfResourceDefinitionDTOObject$`uri`
      self$`label` <- RdfResourceDefinitionDTOObject$`label`
      self$`properties` <- lapply(RdfResourceDefinitionDTOObject$`properties`, function(x) PropertyDTO$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
