# sunagriAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' RdfResourceDTO Class
#'
#' @field uri 
#' @field label 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RdfResourceDTO <- R6::R6Class(
  'RdfResourceDTO',
  public = list(
    `uri` = NULL,
    `label` = NULL,
    initialize = function(`uri`, `label`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
    },
    toJSON = function() {
      RdfResourceDTOObject <- list()
      if (!is.null(self$`uri`)) {
        RdfResourceDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`label`)) {
        RdfResourceDTOObject[['label']] <- self$`label`
      }

      RdfResourceDTOObject
    },
    fromJSON = function(RdfResourceDTOJson) {
      RdfResourceDTOObject <- jsonlite::fromJSON(RdfResourceDTOJson)
      if (!is.null(RdfResourceDTOObject$`uri`)) {
        self$`uri` <- RdfResourceDTOObject$`uri`
      }
      if (!is.null(RdfResourceDTOObject$`label`)) {
        self$`label` <- RdfResourceDTOObject$`label`
      }
    },
    fromJSONObject = function(RdfResourceDTOObject) {
      if (!is.null(RdfResourceDTOObject$`uri`)) {
        self$`uri` <- RdfResourceDTOObject$`uri`
      }
      if (!is.null(RdfResourceDTOObject$`label`)) {
        self$`label` <- RdfResourceDTOObject$`label`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "label": %s
        }',
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`label`,auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(RdfResourceDTOJson) {
      RdfResourceDTOObject <- jsonlite::fromJSON(RdfResourceDTOJson)
      self$`uri` <- RdfResourceDTOObject$`uri`
      self$`label` <- RdfResourceDTOObject$`label`
    }
  )
)
