# sunagriAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' UserDTO Class
#'
#' @field email 
#' @field password 
#' @field firstName 
#' @field familyName 
#' @field address 
#' @field phone 
#' @field affiliation 
#' @field orcid 
#' @field admin 
#' @field groupsUris 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserDTO <- R6::R6Class(
  'UserDTO',
  public = list(
    `email` = NULL,
    `password` = NULL,
    `firstName` = NULL,
    `familyName` = NULL,
    `address` = NULL,
    `phone` = NULL,
    `affiliation` = NULL,
    `orcid` = NULL,
    `admin` = NULL,
    `groupsUris` = NULL,
    initialize = function(`email`, `password`, `firstName`, `familyName`, `address`, `phone`, `affiliation`, `orcid`, `admin`, `groupsUris`){
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!missing(`firstName`)) {
        stopifnot(is.character(`firstName`), length(`firstName`) == 1)
        self$`firstName` <- `firstName`
      }
      if (!missing(`familyName`)) {
        stopifnot(is.character(`familyName`), length(`familyName`) == 1)
        self$`familyName` <- `familyName`
      }
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
      if (!missing(`phone`)) {
        stopifnot(is.character(`phone`), length(`phone`) == 1)
        self$`phone` <- `phone`
      }
      if (!missing(`affiliation`)) {
        stopifnot(is.character(`affiliation`), length(`affiliation`) == 1)
        self$`affiliation` <- `affiliation`
      }
      if (!missing(`orcid`)) {
        stopifnot(is.character(`orcid`), length(`orcid`) == 1)
        self$`orcid` <- `orcid`
      }
      if (!missing(`admin`)) {
        stopifnot(is.character(`admin`), length(`admin`) == 1)
        self$`admin` <- `admin`
      }
      if (!missing(`groupsUris`)) {
        stopifnot(is.list(`groupsUris`), length(`groupsUris`) != 0)
        lapply(`groupsUris`, function(x) stopifnot(is.character(x)))
        self$`groupsUris` <- `groupsUris`
      }
    },
    toJSON = function() {
      UserDTOObject <- list()
      if (!is.null(self$`email`)) {
        UserDTOObject[['email']] <- self$`email`
      }
      if (!is.null(self$`password`)) {
        UserDTOObject[['password']] <- self$`password`
      }
      if (!is.null(self$`firstName`)) {
        UserDTOObject[['firstName']] <- self$`firstName`
      }
      if (!is.null(self$`familyName`)) {
        UserDTOObject[['familyName']] <- self$`familyName`
      }
      if (!is.null(self$`address`)) {
        UserDTOObject[['address']] <- self$`address`
      }
      if (!is.null(self$`phone`)) {
        UserDTOObject[['phone']] <- self$`phone`
      }
      if (!is.null(self$`affiliation`)) {
        UserDTOObject[['affiliation']] <- self$`affiliation`
      }
      if (!is.null(self$`orcid`)) {
        UserDTOObject[['orcid']] <- self$`orcid`
      }
      if (!is.null(self$`admin`)) {
        UserDTOObject[['admin']] <- self$`admin`
      }
      if (!is.null(self$`groupsUris`)) {
        UserDTOObject[['groupsUris']] <- self$`groupsUris`
      }

      UserDTOObject
    },
    fromJSON = function(UserDTOJson) {
      UserDTOObject <- jsonlite::fromJSON(UserDTOJson)
      if (!is.null(UserDTOObject$`email`)) {
        self$`email` <- UserDTOObject$`email`
      }
      if (!is.null(UserDTOObject$`password`)) {
        self$`password` <- UserDTOObject$`password`
      }
      if (!is.null(UserDTOObject$`firstName`)) {
        self$`firstName` <- UserDTOObject$`firstName`
      }
      if (!is.null(UserDTOObject$`familyName`)) {
        self$`familyName` <- UserDTOObject$`familyName`
      }
      if (!is.null(UserDTOObject$`address`)) {
        self$`address` <- UserDTOObject$`address`
      }
      if (!is.null(UserDTOObject$`phone`)) {
        self$`phone` <- UserDTOObject$`phone`
      }
      if (!is.null(UserDTOObject$`affiliation`)) {
        self$`affiliation` <- UserDTOObject$`affiliation`
      }
      if (!is.null(UserDTOObject$`orcid`)) {
        self$`orcid` <- UserDTOObject$`orcid`
      }
      if (!is.null(UserDTOObject$`admin`)) {
        self$`admin` <- UserDTOObject$`admin`
      }
      if (!is.null(UserDTOObject$`groupsUris`)) {
        self$`groupsUris` <- UserDTOObject$`groupsUris`
      }
    },
    fromJSONObject = function(UserDTOObject) {
      if (!is.null(UserDTOObject$`email`)) {
        self$`email` <- UserDTOObject$`email`
      }
      if (!is.null(UserDTOObject$`password`)) {
        self$`password` <- UserDTOObject$`password`
      }
      if (!is.null(UserDTOObject$`firstName`)) {
        self$`firstName` <- UserDTOObject$`firstName`
      }
      if (!is.null(UserDTOObject$`familyName`)) {
        self$`familyName` <- UserDTOObject$`familyName`
      }
      if (!is.null(UserDTOObject$`address`)) {
        self$`address` <- UserDTOObject$`address`
      }
      if (!is.null(UserDTOObject$`phone`)) {
        self$`phone` <- UserDTOObject$`phone`
      }
      if (!is.null(UserDTOObject$`affiliation`)) {
        self$`affiliation` <- UserDTOObject$`affiliation`
      }
      if (!is.null(UserDTOObject$`orcid`)) {
        self$`orcid` <- UserDTOObject$`orcid`
      }
      if (!is.null(UserDTOObject$`admin`)) {
        self$`admin` <- UserDTOObject$`admin`
      }
      if (!is.null(UserDTOObject$`groupsUris`)) {
        self$`groupsUris` <- UserDTOObject$`groupsUris`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "email": %s,
           "password": %s,
           "firstName": %s,
           "familyName": %s,
           "address": %s,
           "phone": %s,
           "affiliation": %s,
           "orcid": %s,
           "admin": %s,
           "groupsUris": [%s]
        }',
        jsonlite::toJSON(self$`email`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`password`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`firstName`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`familyName`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`address`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`phone`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`affiliation`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`orcid`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`admin`,auto_unbox=TRUE, null = "null"),
        lapply(self$`groupsUris`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(UserDTOJson) {
      UserDTOObject <- jsonlite::fromJSON(UserDTOJson)
      self$`email` <- UserDTOObject$`email`
      self$`password` <- UserDTOObject$`password`
      self$`firstName` <- UserDTOObject$`firstName`
      self$`familyName` <- UserDTOObject$`familyName`
      self$`address` <- UserDTOObject$`address`
      self$`phone` <- UserDTOObject$`phone`
      self$`affiliation` <- UserDTOObject$`affiliation`
      self$`orcid` <- UserDTOObject$`orcid`
      self$`admin` <- UserDTOObject$`admin`
      self$`groupsUris` <- UserDTOObject$`groupsUris`
    }
  )
)
