# openSilexSandBoxAPI
#
# An instance of OpenSILEX WebService
#
# OpenAPI spec version: 3.3.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Vector Class
#'
#' @field uri 
#' @field rdfType 
#' @field label 
#' @field brand 
#' @field serialNumber 
#' @field inServiceDate 
#' @field dateOfPurchase 
#' @field personInCharge 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Vector <- R6::R6Class(
  'Vector',
  public = list(
    `uri` = NULL,
    `rdfType` = NULL,
    `label` = NULL,
    `brand` = NULL,
    `serialNumber` = NULL,
    `inServiceDate` = NULL,
    `dateOfPurchase` = NULL,
    `personInCharge` = NULL,
    initialize = function(`uri`, `rdfType`, `label`, `brand`, `serialNumber`, `inServiceDate`, `dateOfPurchase`, `personInCharge`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`rdfType`)) {
        stopifnot(is.character(`rdfType`), length(`rdfType`) == 1)
        self$`rdfType` <- `rdfType`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`brand`)) {
        stopifnot(is.character(`brand`), length(`brand`) == 1)
        self$`brand` <- `brand`
      }
      if (!missing(`serialNumber`)) {
        stopifnot(is.character(`serialNumber`), length(`serialNumber`) == 1)
        self$`serialNumber` <- `serialNumber`
      }
      if (!missing(`inServiceDate`)) {
        stopifnot(is.character(`inServiceDate`), length(`inServiceDate`) == 1)
        self$`inServiceDate` <- `inServiceDate`
      }
      if (!missing(`dateOfPurchase`)) {
        stopifnot(is.character(`dateOfPurchase`), length(`dateOfPurchase`) == 1)
        self$`dateOfPurchase` <- `dateOfPurchase`
      }
      if (!missing(`personInCharge`)) {
        stopifnot(is.character(`personInCharge`), length(`personInCharge`) == 1)
        self$`personInCharge` <- `personInCharge`
      }
    },
    toJSON = function() {
      VectorObject <- list()
      if (!is.null(self$`uri`)) {
        VectorObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`rdfType`)) {
        VectorObject[['rdfType']] <- self$`rdfType`
      }
      if (!is.null(self$`label`)) {
        VectorObject[['label']] <- self$`label`
      }
      if (!is.null(self$`brand`)) {
        VectorObject[['brand']] <- self$`brand`
      }
      if (!is.null(self$`serialNumber`)) {
        VectorObject[['serialNumber']] <- self$`serialNumber`
      }
      if (!is.null(self$`inServiceDate`)) {
        VectorObject[['inServiceDate']] <- self$`inServiceDate`
      }
      if (!is.null(self$`dateOfPurchase`)) {
        VectorObject[['dateOfPurchase']] <- self$`dateOfPurchase`
      }
      if (!is.null(self$`personInCharge`)) {
        VectorObject[['personInCharge']] <- self$`personInCharge`
      }

      VectorObject
    },
    fromJSON = function(VectorJson) {
      VectorObject <- jsonlite::fromJSON(VectorJson)
      if (!is.null(VectorObject$`uri`)) {
        self$`uri` <- VectorObject$`uri`
      }
      if (!is.null(VectorObject$`rdfType`)) {
        self$`rdfType` <- VectorObject$`rdfType`
      }
      if (!is.null(VectorObject$`label`)) {
        self$`label` <- VectorObject$`label`
      }
      if (!is.null(VectorObject$`brand`)) {
        self$`brand` <- VectorObject$`brand`
      }
      if (!is.null(VectorObject$`serialNumber`)) {
        self$`serialNumber` <- VectorObject$`serialNumber`
      }
      if (!is.null(VectorObject$`inServiceDate`)) {
        self$`inServiceDate` <- VectorObject$`inServiceDate`
      }
      if (!is.null(VectorObject$`dateOfPurchase`)) {
        self$`dateOfPurchase` <- VectorObject$`dateOfPurchase`
      }
      if (!is.null(VectorObject$`personInCharge`)) {
        self$`personInCharge` <- VectorObject$`personInCharge`
      }
    },
    fromJSONObject = function(VectorObject) {
      if (!is.null(VectorObject$`uri`)) {
        self$`uri` <- VectorObject$`uri`
      }
      if (!is.null(VectorObject$`rdfType`)) {
        self$`rdfType` <- VectorObject$`rdfType`
      }
      if (!is.null(VectorObject$`label`)) {
        self$`label` <- VectorObject$`label`
      }
      if (!is.null(VectorObject$`brand`)) {
        self$`brand` <- VectorObject$`brand`
      }
      if (!is.null(VectorObject$`serialNumber`)) {
        self$`serialNumber` <- VectorObject$`serialNumber`
      }
      if (!is.null(VectorObject$`inServiceDate`)) {
        self$`inServiceDate` <- VectorObject$`inServiceDate`
      }
      if (!is.null(VectorObject$`dateOfPurchase`)) {
        self$`dateOfPurchase` <- VectorObject$`dateOfPurchase`
      }
      if (!is.null(VectorObject$`personInCharge`)) {
        self$`personInCharge` <- VectorObject$`personInCharge`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "rdfType": %s,
           "label": %s,
           "brand": %s,
           "serialNumber": %s,
           "inServiceDate": %s,
           "dateOfPurchase": %s,
           "personInCharge": %s
        }',
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`rdfType`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`label`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`brand`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`serialNumber`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`inServiceDate`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`dateOfPurchase`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`personInCharge`,auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(VectorJson) {
      VectorObject <- jsonlite::fromJSON(VectorJson)
      self$`uri` <- VectorObject$`uri`
      self$`rdfType` <- VectorObject$`rdfType`
      self$`label` <- VectorObject$`label`
      self$`brand` <- VectorObject$`brand`
      self$`serialNumber` <- VectorObject$`serialNumber`
      self$`inServiceDate` <- VectorObject$`inServiceDate`
      self$`dateOfPurchase` <- VectorObject$`dateOfPurchase`
      self$`personInCharge` <- VectorObject$`personInCharge`
    }
  )
)
